CREATE SCHEMA IF NOT EXISTS `USER`;

CREATE TABLE IF NOT EXISTS `USER`.`USER_ACCOUNT` (
    ID VARCHAR(36) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLES VARCHAR(255) ARRAY NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NULL,
    VERSION BIGINT NULL,
    PRIMARY KEY (ID),
    UNIQUE (EMAIL),
    UNIQUE (USERNAME)
);

CREATE TABLE IF NOT EXISTS `USER`.`USER_ACCOUNT_TOKEN` (
    ID VARCHAR(36) NOT NULL,
    `VALUE` VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    VERSION BIGINT NULL,
    UNIQUE (ID, `VALUE`)
);
