CREATE SCHEMA IF NOT EXISTS `CATALOG`;

CREATE TABLE IF NOT EXISTS `CATALOG`.`CATEGORY` (
    ID VARCHAR(36) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    PARENT_ID VARCHAR(36) NULL DEFAULT NULL,
    VERSION BIGINT NULL,
    PRIMARY KEY (id),
    UNIQUE (CODE)
);
CREATE TABLE IF NOT EXISTS `CATALOG`.`CATEGORY_CHILD` (
    ID VARCHAR(36) NOT NULL,
    CHILD_ID VARCHAR(36) NOT NULL,
    UNIQUE (ID, CHILD_ID)
);

CREATE TABLE IF NOT EXISTS `CATALOG`.`PRODUCT` (
    ID VARCHAR(36) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VERSION BIGINT NULL,
    PRIMARY KEY (ID),
    UNIQUE (CODE)
);
CREATE TABLE IF NOT EXISTS `CATALOG`.`PRODUCT_CATEGORY` (
    ID VARCHAR(36) NOT NULL,
    CATEGORY_ID VARCHAR(36) NOT NULL,
    UNIQUE (ID, CATEGORY_ID)
);
CREATE TABLE IF NOT EXISTS `CATALOG`.`PRODUCT_ITEM` (
    ID VARCHAR(36) NOT NULL,
    PRODUCT_ID VARCHAR(36) NOT NULL,
    SKU_ID VARCHAR(36) NOT NULL,
    PRICE_NUMBER DOUBLE NOT NULL,
    PRICE_CURRENCY VARCHAR(36) NOT NULL,
    BASE BOOL NOT NULL,
    VERSION BIGINT NULL,
    PRIMARY KEY (ID)
);
